version: '3'

vars:
  IMAGE_REGISTRY: git.moekai.net
  IMAGE_REPOSITORY: irfan
  IMAGE_NAME: mocha
  IMAGE_ARCH: linux/amd64,linux/arm/v7,linux/arm64/v8
  VERSION:
    sh: node -p "try { require('./package.json').version } catch(e) { '' }"
  RELEASE: ""
  TAG:
    sh: |
      VERSION="{{.VERSION}}"
      RELEASE="{{.RELEASE}}"
      BASE="${VERSION:-latest}"
      if [ -n "${RELEASE}" ]; then
        echo "${BASE}-r${RELEASE}"
      else
        echo "${BASE}"
      fi

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list
    silent: true

  build:
    desc: Build site for production
    cmds:
      - npm run build

  clean:
    desc: Remove build artifacts
    cmds:
      - npm run clean
      - rm -f .build.env

  dev:
    desc: Start development server with hot reload
    cmds:
      - npm run start
    ignore_error: true

  install:
    desc: Install dependencies
    cmds:
      - npm install

  version:
    desc: "Update package version (usage: task version TYPE=patch|minor|major|x.x.x)"
    vars:
      TYPE: '{{.TYPE | default "patch"}}'
    cmds:
      - npm version {{.TYPE}} --no-git-tag-version
      - echo "Version updated successfully"

  container:build:all:
    desc: "Build and publish both standard and lean images (usage: task container:build:all [VERSION=x.x.x] [RELEASE=n])"
    cmds:
      - task: container:build:std
      - task: container:build:lean

  container:build:std:
    desc: "Build and publish standard container image (usage: task container:build:std [VERSION=x.x.x] [RELEASE=n])"
    cmds:
      - |
        cat > .build.env <<EOF
        IMAGE_NAME={{.IMAGE_NAME}}
        IMAGE_REGISTRY={{.IMAGE_REGISTRY}}
        IMAGE_REPOSITORY={{.IMAGE_REPOSITORY}}
        IMAGE_ARCH={{.IMAGE_ARCH}}
        IMAGE_DOCKERFILE=Dockerfile
        EOF
      - img-builder -c . -e .build.env -t {{.TAG}}
      - rm -f .build.env

  container:build:lean:
    desc: "Build and publish lean container image (usage: task container:build:lean [VERSION=x.x.x] [RELEASE=n])"
    cmds:
      - |
        cat > .build.env <<EOF
        IMAGE_NAME={{.IMAGE_NAME}}-lean
        IMAGE_REGISTRY={{.IMAGE_REGISTRY}}
        IMAGE_REPOSITORY={{.IMAGE_REPOSITORY}}
        IMAGE_ARCH={{.IMAGE_ARCH}}
        IMAGE_DOCKERFILE=Dockerfile.lean
        EOF
      - img-builder -c . -e .build.env -t {{.TAG}}
      - rm -f .build.env
