version: '3'

vars:
  IMAGE_NAME: mocha
  IMAGE_ARCH: linux/amd64,linux/arm64/v8
  VERSION:
    sh: node -p "try { require('./package.json').version } catch(e) { '' }"
  BRANCH:
    sh: git rev-parse --abbrev-ref HEAD
  RELEASE: ""
  TAG:
    sh: |
      VERSION="{{.VERSION}}"
      BRANCH="{{.BRANCH}}"
      RELEASE="{{.RELEASE}}"
      BASE="${VERSION:-latest}"
      if [ -n "${RELEASE}" ]; then
        echo "${BASE}-${BRANCH}-r${RELEASE}"
      else
        echo "${BASE}"
      fi

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list
    silent: true

  build:
    desc: Build site for production
    cmds:
      - npm run build

  clean:
    desc: Remove build artifacts
    cmds:
      - npm run clean
      - rm -f .build.env

  dev:
    desc: Start development server with hot reload
    cmds:
      - npm run start
    ignore_error: true

  install:
    desc: Install dependencies
    cmds:
      - npm install

  version:
    desc: "Update package version (usage: task version TYPE=patch|minor|major|x.x.x)"
    vars:
      TYPE: '{{.TYPE | default "patch"}}'
    cmds:
      - npm version {{.TYPE}} --no-git-tag-version
      - echo "Version updated successfully"

  container:build:all:
    desc: "Build and publish both standard and lean images (usage: task container:build:all [VERSION=x.x.x] [RELEASE=n])"
    cmds:
      - task: container:build:std
      - task: container:build:lean

  container:build:std:
    desc: "Build and publish standard container image (usage: task container:build:std [VERSION=x.x.x] [RELEASE=n])"
    cmds:
      - task: _container:push
        vars:
          NAME: "{{.IMAGE_NAME}}"
          REGISTRY: git.moekai.net
          REPOSITORY: irfan
          DOCKERFILE: Dockerfile
      - task: _container:push
        vars:
          NAME: "{{.IMAGE_NAME}}"
          REGISTRY: ghcr.io
          REPOSITORY: irfanhakim-as
          DOCKERFILE: Dockerfile

  container:build:lean:
    desc: "Build and publish lean container image (usage: task container:build:lean [VERSION=x.x.x] [RELEASE=n])"
    cmds:
      - task: _container:push
        vars:
          NAME: "{{.IMAGE_NAME}}-lean"
          REGISTRY: git.moekai.net
          REPOSITORY: irfan
          DOCKERFILE: Dockerfile.lean
      - task: _container:push
        vars:
          NAME: "{{.IMAGE_NAME}}-lean"
          REGISTRY: ghcr.io
          REPOSITORY: irfanhakim-as
          DOCKERFILE: Dockerfile.lean

  _container:push:
    internal: true
    cmds:
      - |
        cat > .build.env <<EOF
        IMAGE_NAME={{.NAME}}
        IMAGE_REGISTRY={{.REGISTRY}}
        IMAGE_REPOSITORY={{.REPOSITORY}}
        IMAGE_ARCH={{.IMAGE_ARCH}}
        IMAGE_DOCKERFILE={{.DOCKERFILE}}
        EOF
      - img-builder -c . -e .build.env -t {{.TAG}}
      - rm -f .build.env
